name: Release AW PAYMENTS SERVICE PROTO FILES

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protobuf Compiler
        run: sudo apt install protobuf-compiler

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npx semantic-release@^22.0.7
